### ISSUE TITLE
Can I use it without docker and how do I do it？

### ISSUE THREAD

**Issue by 1030366507** [astaka-pe/SeMIGCN#3]

**Comment by astaka-pe** [comment]
@1030366507
There are two options for installation without Docker:

1. Direct installation (not recommended)
You can install the required packages directly via pip, but this isn’t recommended as it might interfere with other projects or your system environment.

2. Conda (recommended)
Creating a virtual environment with Conda is a cleaner option, allowing you to install the necessary packages without affecting your system.

We’ve also set up a branch named [torch-1.7.0](https://github.com/astaka-pe/SeMIGCN/tree/torch-1.7.0), which includes instructions for using Conda. Since it was created a few years ago, some packages may need to be updated.
